import React, { useState, useEffect, useCallback } from 'react';
import { useAuth } from '../contexts/AuthContext';
import { EmptyState } from '../components/common/EmptyState';
import { Button } from '../components/common/Button';
import {
  Bell,
  CheckCheck,
  Trash2,
  AlertCircle,
  Bug,
  Wheat,
  CloudSun,
  ClipboardList,
  Briefcase,
  BookOpen,
  Info,
} from 'lucide-react';
import {
  fetchNotifications,
  markNotificationAsRead,
  markAllNotificationsAsRead,
  deleteNotification,
} from '../services/notificationService';
import { NotificationItem, NotificationType } from '../types';

// ─── Icon per type ────────────────────────────────────────────────────────────
const TYPE_ICON: Record<NotificationType, React.ReactNode> = {
  activity_reminder:  <ClipboardList className="w-4 h-4" />,
  pest_follow_up:     <Bug className="w-4 h-4" />,
  harvest_reminder:   <Wheat className="w-4 h-4" />,
  scheduled_activity: <ClipboardList className="w-4 h-4" />,
  weather_indicator:  <CloudSun className="w-4 h-4" />,
  advisory_update:    <BookOpen className="w-4 h-4" />,
  job_inquiry:        <Briefcase className="w-4 h-4" />,
};

const TYPE_COLOR: Record<NotificationType, string> = {
  activity_reminder:  'bg-blue-100 text-blue-700',
  pest_follow_up:     'bg-rose-100 text-rose-700',
  harvest_reminder:   'bg-amber-100 text-amber-700',
  scheduled_activity: 'bg-blue-100 text-blue-700',
  weather_indicator:  'bg-sky-100 text-sky-700',
  advisory_update:    'bg-emerald-100 text-emerald-700',
  job_inquiry:        'bg-indigo-100 text-indigo-700',
};

// ─── Page ─────────────────────────────────────────────────────────────────────
export const NotificationsPage: React.FC = () => {
  const { user } = useAuth();
  const [notifications, setNotifications] = useState<NotificationItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [actionLoading, setActionLoading] = useState<string | null>(null);

  const load = useCallback(async () => {
    if (!user?.id) return;
    setLoading(true);
    const data = await fetchNotifications(user.id);
    setNotifications(data);
    setLoading(false);
  }, [user]); // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => { load(); }, [load]);

  const handleMarkRead = async (id: string) => {
    setActionLoading(id);
    await markNotificationAsRead(id);
    setNotifications(prev =>
      prev.map(n => n.id === id ? { ...n, is_read: true } : n)
    );
    setActionLoading(null);
  };

  const handleMarkAllRead = async () => {
    if (!user?.id) return;
    setActionLoading('all');
    await markAllNotificationsAsRead(user.id);
    setNotifications(prev => prev.map(n => ({ ...n, is_read: true })));
    setActionLoading(null);
  };

  const handleDelete = async (id: string) => {
    setActionLoading(id + '-del');
    await deleteNotification(id);
    setNotifications(prev => prev.filter(n => n.id !== id));
    setActionLoading(null);
  };

  const unreadCount = notifications.filter(n => !n.is_read).length;

  if (loading) {
    return (
      <div className="py-20 text-center">
        <div className="w-8 h-8 border-2 border-emerald-500 border-t-transparent rounded-full animate-spin mx-auto mb-3" />
        <p className="text-sm text-slate-500">Loading notifications…</p>
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-in fade-in duration-200">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <h1 className="text-2xl font-extrabold text-slate-900 tracking-tight">Notifications</h1>
            {unreadCount > 0 && (
              <span className="inline-flex items-center justify-center w-6 h-6 rounded-full bg-rose-500 text-white text-[11px] font-bold shrink-0">
                {unreadCount}
              </span>
            )}
          </div>
          <p className="text-xs text-slate-500">
            Activity reminders, pest follow-ups, harvest alerts, and advisory updates.
          </p>
        </div>

        {unreadCount > 0 && (
          <Button
            variant="outline"
            size="sm"
            icon={<CheckCheck className="w-4 h-4" />}
            loading={actionLoading === 'all'}
            onClick={handleMarkAllRead}
          >
            Mark all as read
          </Button>
        )}
      </div>

      {/* How notifications are generated */}
      <div className="bg-blue-50 border border-blue-200 rounded-2xl p-4 flex items-start gap-3 text-xs">
        <Info className="w-4 h-4 text-blue-600 shrink-0 mt-0.5" />
        <p className="text-blue-800">
          <strong>About these notifications:</strong> Notifications are generated by farm actions such as
          recording a pest observation (pest follow-up reminder), scheduling an activity, or receiving a
          farm-work inquiry. They are stored in your Supabase account and private to you.
        </p>
      </div>

      {/* Notifications list */}
      {notifications.length === 0 ? (
        <EmptyState
          icon={<Bell className="w-10 h-10 text-slate-300" />}
          title="No notifications yet"
          description="Notifications will appear here as you use the platform — pest follow-up reminders, harvest alerts, activity reminders, and more."
        />
      ) : (
        <div className="space-y-2">
          {notifications.map(n => (
            <div
              key={n.id}
              className={`bg-white rounded-2xl border transition-colors ${
                n.is_read ? 'border-slate-200/80' : 'border-emerald-300 shadow-xs shadow-emerald-100'
              }`}
            >
              <div className="flex items-start gap-3 p-4">
                {/* Icon */}
                <div className={`w-9 h-9 rounded-xl flex items-center justify-center shrink-0 ${
                  TYPE_COLOR[n.type] ?? 'bg-slate-100 text-slate-500'
                }`}>
                  {TYPE_ICON[n.type]}
                </div>

                {/* Content */}
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <p className={`text-sm font-bold ${n.is_read ? 'text-slate-700' : 'text-slate-900'}`}>
                      {n.title}
                    </p>
                    {!n.is_read && (
                      <span className="w-2 h-2 rounded-full bg-emerald-500 shrink-0" />
                    )}
                  </div>
                  <p className="text-xs text-slate-600 mt-0.5 leading-relaxed">{n.message}</p>
                  <p className="text-[10px] text-slate-400 mt-1">
                    {new Date(n.created_at).toLocaleString(undefined, {
                      day: 'numeric', month: 'short', year: 'numeric',
                      hour: '2-digit', minute: '2-digit',
                    })}
                    {' · '}
                    <span className="capitalize">{n.type.replace(/_/g, ' ')}</span>
                  </p>
                </div>

                {/* Actions */}
                <div className="flex items-center gap-1 shrink-0">
                  {!n.is_read && (
                    <button
                      onClick={() => handleMarkRead(n.id)}
                      disabled={actionLoading === n.id}
                      className="p-1.5 text-slate-400 hover:text-emerald-600 rounded-lg transition-colors cursor-pointer"
                      title="Mark as read"
                    >
                      <CheckCheck className="w-3.5 h-3.5" />
                    </button>
                  )}
                  <button
                    onClick={() => handleDelete(n.id)}
                    disabled={actionLoading === n.id + '-del'}
                    className="p-1.5 text-slate-400 hover:text-rose-600 rounded-lg transition-colors cursor-pointer"
                    title="Delete notification"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {notifications.length > 0 && (
        <div className="flex justify-center">
          <button
            onClick={load}
            className="text-xs font-semibold text-emerald-700 hover:underline cursor-pointer"
          >
            Refresh notifications
          </button>
        </div>
      )}
    </div>
  );
};
